version: '3.8'

services:
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    container_name: leany-web
    restart: unless-stopped
    ports:
      - "${WEB}:3000"

  api:
    build:
      context: ../api
      dockerfile: Dockerfile.fastapi
    container_name: leany-api
    restart: unless-stopped
    ports:
      - "${FASTAPI_PORT}:8000"
    environment:
      - MINIO_API_PORT=${MINIO_API_PORT}
      - MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    depends_on:
      - minio
    command: uvicorn main:app --host 0.0.0.0 --port ${FASTAPI_PORT} --reload

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    env_file:
      - .env.minio

volumes:
  minio-data:
