version: '3.8'

services:
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    container_name: nextjs-web
    restart: unless-stopped
    expose:
      - 3003

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8300:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    restart: unless-stopped

# 预留 api 服务，后续可启用
#  api:
#    build:
#      context: ../api
#      dockerfile: Dockerfile
#    container_name: backend-api
#    restart: unless-stopped
#    expose:
#      - 5001
