
name: Compose Integration Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compose-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compose up (web + minio)
        working-directory: ./docker
        run: |
          docker compose up -d --build

      - name: Wait for MinIO to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 9000 && break
            sleep 2
          done
          if ! nc -z localhost 9000; then
            echo "MinIO did not start in time" >&2
            docker compose -f docker/docker-compose.yml logs minio || true
            exit 1
          fi

      - name: Wait for Web to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 8301 && break
            sleep 2
          done
          if ! nc -z localhost 8301; then
            echo "Web did not start in time" >&2
            docker compose -f docker/docker-compose.yml logs leany-web || true
            exit 1
          fi

      - name: Run backend tests
        working-directory: ./api
        run: |
          pip install uv
          uv venv
          uv pip install -r requirements.txt
          uv run python test_minio_api.py

      - name: Run frontend lint & build
        working-directory: ./web
        run: |
          corepack enable
          corepack prepare pnpm@10.0.0 --activate
          pnpm install --frozen-lockfile
          pnpm lint
          pnpm build

      - name: Compose down
        if: always()
        working-directory: ./docker
        run: docker compose down -v