
name: Compose Integration Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compose-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compose up (web + minio + api)
        working-directory: ./docker
        run: |
          docker compose up -d --build

      - name: Compose down
        if: always()
        working-directory: ./docker
        run: docker compose down -v